name: Python Workflow with Caching

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python and cache virtual environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Create and start a virtual environment
        run: python -m venv venv

      - name: Install dependencies and cache virtual environment
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Caching the virtual environment
      - name: Cache virtual environment
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Restore cached virtual environment
      - name: Restore virtual environment from cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Set up Python and activate virtual environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # Activating the virtual environment
      - name: Activate virtual environment
        run: source ./venv/bin/activate

      - name: Run tests with pytest
        run: pytest

