name: Codebase test and linting

# Triggers
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
            
      - name: Setup the virtual environment 
        run: |
          python -m venv .venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Installed Packages:"
          pip list

      - name: Cache the virtual environment
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./.venv
          key: ${{ runner.os }}-tapan
          restore-keys: ${{ runner.os }}-tapan

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore virtual environment from cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./.venv
          key: ${{ runner.os }}-tapan
          restore-keys: ${{ runner.os }}-tapan

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run the tests 
        run: |
          echo "Operating System: $(uname -a)"
          echo "Python Version: $(python --version)"
          echo "pip Version: $(pip --version)"
          echo "Installed Packages:"
          pip list
          pytest

