name: Codebase test and linting

# Triggers
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
            
      - name: Setup the virtual environment 
        run: |
          python -m venv .venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache the virtual environment
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip

  lint-code:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore virtual environment 
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run the tests 
        run: |
          . .venv/bin/activate
          flake8 ./ --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv

  test:
    runs-on: ubuntu-latest
    needs: lint-code
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore virtual environment 
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run the tests 
        run: |
          . .venv/bin/activate
          pytest

